Financial-Times/n-logger

main.js
Currently error output is suppressed when testing
=> Log errors when testing

lib/format-meta.js, test/lib/format-meta.test.js
Handle non-string values and values without spaces
=> Correct logging format

.eslintrc, README.md, lib/agent.js, lib/transports/splunk.js, main.js, test/lib/agent.test.js, test/lib/format-meta.test.js, test/lib/transports/splunk.test.js, test/logger.test.js
=> More fine-grained usage

README.md, main.js
=> allow console logger level to be overriden by env var

package.json
=> Update: request version to ^2.67.0

README.md, package.json, src/lib/formatter.js, src/lib/non-empty.js, src/lib/transports/splunk.js, src/main.js, test/lib/format-message.test.js, test/lib/formatter.test.js, test/lib/transports/splunk.test.js
Pulls out message and stack trace
=> Handle Error objects being passed in

src/main.js
Keep things backwards-compatiable (ish)
=> Put `log` method back in

README.md, package.json, src/lib/formatter.js, src/lib/logger.js, src/lib/transports/splunk.js, test/lib/logger.test.js
i.e. meta to send with every log call
=> Ability to add context

.npmignore, n.Makefile, package.json
* update makefile
* lates node modules
=> Spring clean

src/lib/app-logger.js
=> Colourize winston logs

package.json, src/lib/app-logger.js
=> Re-colourise winston logs

.circleci/config.yml
=> ci config update

src/main.js
=> loads fetch first

src/lib/formatHEC.js, src/lib/transports/splunkHEC.js, test/lib/formatHEC.test.js
=> format data sent to splunk HEC

src/lib/transports/splunkHEC.js, test/lib/formatHEC.test.js
=> splunk HEC refactor

src/lib/logger.js
Hopefully this will fix the above log salad.
=> Update logger.js: Be cool with strings

src/lib/transports/splunkHEC.js
Reverts Financial-Times/n-logger#68
=> Revert "add optional deploymentStage splunk log date"

src/main.js
=> Add check for a special param to allow opt-in to non-prod splunk logging

README.md
🐿 v2.11.0
Added some bits and pieces which I thought might be useful.
=> Update the readme with instructions on testing locally

package-lock.json, package.json
This recreates #153 which has conflicts that I can't be bothered to resolve. Fixes a potential security vulnerability.
=> Bump Winston to 2.4.6

README.md
This should be merged on 17th April 2023.
=> Confirm deprecation dates
